version: '3'
services:
  mssql:
    image: 'microsoft/mssql-server-linux:2017-latest'
    container_name: mssql-synel
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: '123456'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: Developer
